version: 3

includes:
  one-folder:
    taskfile: one-folder/Taskfile.yml
    dir: one-folder
  another-folder:
    taskfile: another-folder/Taskfile.yml
    dir: another-folder

tasks:
  pwd:
    cmds:
      - echo $PWD

  all-pwds:
    cmds:
      - task: one-folder:pwd
      - task: another-folder:pwd
      - task: pwd
