---
services:
  node-one-folder:
    image: node:20.16-alpine
    command: ['/bin/sh', '-c', 'ls -l /app && echo ${PWD}']
    volumes:
      - volume-one-folder:/app

volumes:
  volume-one-folder:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PWD}'
