version: 3

includes:
  one-folder:
    taskfile: ../one-folder/Taskfile.yml
    dir: ../one-folder
    optional: true
    internal: true
  another-folder:
    taskfile: ../another-folder/Taskfile.yml
    dir: ../another-folder
    optional: true
    internal: true

tasks:
  start:
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --remove-orphans
      - docker-compose -f docker-compose.yml -f docker-compose.override.yml logs
  stop:
    cmds:
      - docker-compose -f docker-compose.yml -f docker-compose.override.yml down -v

  all-start:
    cmds:
      - task: one-folder:start
      - task: another-folder:start
      - task: start

  all-stop:
    cmds:
      - task: one-folder:stop
      - task: another-folder:stop
      - task: stop
