version: 3

includes:
  one-folder:
    taskfile: ../one-folder/Taskfile.yml
    dir: ../one-folder
    optional: true
    internal: true
  another-folder:
    taskfile: ../another-folder/Taskfile.yml
    dir: ../another-folder
    optional: true
    internal: true

tasks:
  start:
    cmds:
      - echo $PWD
      - "PWD={{.TASKFILE_DIR}} docker-compose up --remove-orphans"
      - docker-compose down -v

  all-start:
    cmds:
      - task: one-folder:start
      - task: another-folder:start
      - task: start
